In [33]:
import numpy as np

# Define the matrix
A = np.array([[1, 0, 1],
              [-1, 1, 0]])

# Compute the SVD of the matrix
U, S, V = np.linalg.svd(A,full_matrices=True)


In [34]:
print(U)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [35]:
print(S)

[1.73205081 1.        ]


In [36]:
print(V)

[[ 8.16496581e-01 -4.08248290e-01  4.08248290e-01]
 [-4.40677305e-16  7.07106781e-01  7.07106781e-01]
 [-5.77350269e-01 -5.77350269e-01  5.77350269e-01]]
